JacksonBurns/astartes

astartes/samplers/sampler.py
get_next_sample() to get_sample(); rename get_batch_samples()  to get_batch_sample()
=> Rename abstract_sampler methods for grammatical consistency

astartes/samplers/__init__.py, astartes/samplers/interpolation/kennardstone.py, test/samplers/test_kennard_stone.py
=> Updated Implementation and Unit Testing for Kennard-Stone Sampler

README.md, astartes/main.py, astartes/samplers/__init__.py, astartes/samplers/extrapolation/__init__.py, astartes/samplers/extrapolation/kmeans.py, astartes/samplers/extrapolation/sphere_exclusion.py, astartes/samplers/interpolation/__init__.py, astartes/samplers/interpolation/sphere_exclusion.py, docs/conf.py, pyproject.toml, test/samplers/test_sphere_exclusion.py, test/test_astartes.py, test/test_molecules.py, test/utils/test_exceptions.py
=> move sphere_exclusion, add fxn/test headers and imports

.github/workflows/run_tests.yml, astartes/molecules.py, astartes/utils/exceptions.py, test/samplers/test_random.py, test/utils/test_exceptions.py, test/utils/test_sampler_factory.py
=> add test for random and sampler factory

.github/workflows/gen_docs.yml, docs/index.rst, sklearn_to_astartes.md
=> add transition to astartes docs page

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE/bugfix.md, .github/PULL_REQUEST_TEMPLATE/new_feature.md, README.md, pyproject.toml
Resolve #36 and resolve #37 
The README will be continually updated as we add the remaining few samplers, but this is the last major overhaul it will need (FLW).
=> README Update, PR and Issue Templates, Developer Instructions

astartes/samplers/extrapolation/kmeans.py
This PR makes allows all arguments from sklearn's kmean clustering algorithm accessible to users.
=> Allow arguments for KMeans to be accessible to users

astartes/samplers/extrapolation/scaffold.py, pyproject.toml
=> fix issue with missing packages, bump beta version

.github/workflows/check_pypi_build.yml, .github/workflows/format_code.yml, .github/workflows/update_joss_branch.yml, .gitignore, LICENSE, README.md, sklearn_to_astartes.md
minor technical updates for repo update
=> Repo meta fixes

paper.bib, paper.md
This minor PR adds a few more references to other papers in which people have discussed the importance of creating more challenging data splits. It also fixes a typo and just cleans up the .bib file by removing the unused entries. Happy to hear feedback!
=> Minor paper edits

.github/workflows/reproduce_paper.yml, astartes/main.py, astartes/molecules.py, examples/reproduce_paper_splits/validate_splits.py
Should be exactly reproducible between runs, which this alternate testing approach was demonstrating in just a very roundabout way anyway.
=> Small Bugfixes for v1.0.0

paper.md
This PR incorporates some feedback from Bill after a first-pass of reading the paper. 
WIP label because I will figure how to acknowledge funding support soon.
=> Paper edits

README.md, astartes/main.py, astartes/utils/array_type_helpers.py, pyproject.toml, test/unit/utils/test_convert_to_array.py
This PR is attempting to add support for Pandas Dataframes and Series directly.
Resolves #125
=> Support for Pandas Dataframe and Series

CONTRIBUTING.md, astartes/samplers/abstract_sampler.py, astartes/samplers/extrapolation/scaffold.py, astartes/samplers/extrapolation/time_based.py, astartes/samplers/interpolation/kennardstone.py, astartes/samplers/interpolation/spxy.py, astartes/utils/fast_kennard_stone.py
This PR is some simple internal refactoring to make things more flexible, maintainable, etc. - will add more detailed descriptions in each commit
=> Internal Improvements

CONTRIBUTING.md, README.md
This pull request contains updates to the documentation as part of the PyOpenSci review (see https://github.com/pyOpenSci/software-submission/issues/120).
Each commit message contains additional clarifying details.
=> PyOpenSci Review - Documentation Updates

README.md, astartes/__init__.py
- final edits for pyOpenSci release
- need to add a minor release to trigger a zenodo release
=> Final Wrap-up Edits for pyOpenSci Zenodo Release

.github/workflows/run_tests.yml, README.md, astartes/__init__.py, pyproject.toml
=> add python 3.12 to ci, pyproject, readme - bump patch version 4 release

astartes/samplers/extrapolation/scaffold.py
This PR fixes minor issues within scaffold.py related to whitespace formatting and the error message.
=> Fix scaffold formatting

astartes/samplers/interpolation/mlm.py
=> Implementing the MLM Sampler

.github/workflows/reproduce_paper.yml
Paper was run pre-numpy 2 - need to keep that restriction here
=> fix failing paper reproduction ci

astartes/__init__.py, astartes/utils/array_type_helpers.py
Resolves https://github.com/JacksonBurns/astartes/issues/180
@knathanm thanks for reporting!
=> Use `len` instead of `any` when returing `val` indexes
